version: "2.10"

volumes:
  couchdb_data:

services:
  fastapi:
    build:
      context: .
      dockerfile: ./.docker/Dockerfile
    depends_on:
      - couchdb
    ports:
      - 8000:8000


  couchdb:
    image: couchdb
    restart: always
    environment:
      - COUCHDB_USER=
      - COUCHDB_PASSWORD=
    volumes:
      - couchdb_data:/opt/couchdb/data




