class Productivity:
    def set_qualification(self, qualification_: int) -> None: ...
    def get_qualification(self) -> int: ...
    qualification: int = property(fget=get_qualification, fset=set_qualification,
                            fdel=None, doc="The qualification property")


    def set_count(self, count_: int) -> None: ...
    def get_count(self) -> int: ...
    count = property(fget=get_count, fset=set_count, fdel=None, doc="The count property")

    def get_motivation(self) -> float: ...
    motivation = property(fset=None, fget=get_motivation, fdel=None,
                            doc="The motivation readonly property")

    def get_productivity(self) -> float: ...
    productivity = property(fset=None, fget=get_productivity, fdel=None,
                            doc="The productivity readonly property")
