class Productivity:
    def calc_motivation(self) -> None: ...
    def calc_productivity(self) -> None: ...

    def update_productivity(self) -> None: ...

    def set_qualification(self, qualification_: int) -> None: ...
    def set_count(self, count_: int) -> None: ...

    def get_productivity(self) -> float: ...
